name: loreon workflow

on: 
    push:
    workflow_dispatch:

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps: 
            - name: welcome message
              run: echo "my first workflow on github"

            - name: List Files
              run: ls

            - name: Read file
              run: cat README.md